index:
    path: /
    controller: LaSalle\App\Film\Controller\SayHelloController::index

getFilmById:
    path: /film/{filmId}
    controller: LaSalle\App\Film\Controller\GetFilmByIdController::apply
    methods: GET

createFilm:
    path: /film
    controller: LaSalle\App\Film\Controller\CreateFilmController::apply
    methods: POST

listProducts:
    path: /product
    controller: LaSalle\App\Film\Controller\ListProductsController::apply
    methods: GET

createProduct:
    path: /product
    controller: LaSalle\App\Film\Controller\CreateProductController::apply
    methods: POST

deleteProductById:
    path: /product/{id}
    controller: LaSalle\App\Film\Controller\DeleteProductByIdController::apply
    methods: DELETE

updateProductById:
    path: /product/{id}
    controller: LaSalle\App\Film\Controller\UpdateProductByIdController::apply
    methods: PUT

createOwner:
    path: /owner
    controller: LaSalle\App\Film\Controller\CreateOwnerController::apply
    methods: POST

listOwners:
    path: /owner
    controller: LaSalle\App\Film\Controller\ListOwnersController::apply
    methods: GET

listProductsGui:
    path: /gui/product
    controller: LaSalle\App\Film\Controller\ListProductsGuiController::apply
    methods: GET