index:
    path: /
    controller: App\Controller\SayHelloController::index

postRequest:
    path: /request
    controller: App\Controller\RequestTestController::postRequest
    methods: [POST]

getRequest:
    path: /request
    controller: App\Controller\RequestTestController::getRequest