index:
    path: /
    controller: LaSalle\App\Film\Controller\SayHelloController::index

getFilmById:
    path: /film/{filmId}
    controller: LaSalle\App\Film\Controller\GetFilmByIdController::apply
    methods: GET
